<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="sivaji" failures="1" tests="2" name="Error Validations Test Result" time="31.131" errors="0" timestamp="2024-10-17T09:40:38 CDT">
  <testcase classname="rahulshettyacademy.Tests.ErrorValidationsTest" name="loginErrorValidation" time="1.236"/>
  <testcase classname="rahulshettyacademy.Tests.ErrorValidationsTest" name="productErrorValidation" time="16.557">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rahulshettyacademy.Tests.ErrorValidationsTest.productErrorValidation(ErrorValidationsTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validations Test Result -->
